minimum_pre_commit_version: "3.2.0"

default_language_version:
  python: python3.11

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-yaml

  - repo: local
    hooks:
      - id: mypy
        name: mypy
        entry: poetry run mypy --config-file=pyproject.toml
        language: system
        types: [python]
        require_serial: true

      - id: ruff-lint
        name: ruff lint
        entry: poetry run ruff check --fix
        language: system
        types: [python, toml]

      - id: ruff-format
        name: ruff format
        entry: poetry run ruff format
        language: system
        types: [python, toml]

      - id: flake8
        name: flake8
        entry: poetry run flake8
        language: system
        types: [python]

