"""make serial number unique

Revision ID: 43a05c5917d6
Revises: 7f57c694ed93
Create Date: 2025-04-11 04:49:40.444024

"""

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "43a05c5917d6"
down_revision: str | None = "7f57c694ed93"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

SERIAL_NUMBER_CONSTRAINT = "uq_devices_serial_number"


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(SERIAL_NUMBER_CONSTRAINT, "devices", ["serial_number"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(SERIAL_NUMBER_CONSTRAINT, "devices", type_="unique")
    # ### end Alembic commands ###
